import jsPDF from 'jspdf';

/** Strip common markdown syntax for plain-text PDF output */
export const markdownToPlainText = (markdown) => {
  if (!markdown) return '';
  return markdown
    .replace(/^#{1,6}\s+/gm, '')
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/\*(.+?)\*/g, '$1')
    .replace(/__(.+?)__/g, '$1')
    .replace(/_(.+?)_/g, '$1')
    .replace(/`{1,3}([^`]+)`{1,3}/g, '$1')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/^>\s+/gm, '')
    .replace(/^[-*+]\s+/gm, '• ')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
};

const sanitizeFilename = (topic) =>
  `Literai_${topic.substring(0, 40).replace(/[^\w\s-]/g, '').replace(/\s+/g, '_')}.pdf`;

/**
 * Export full report to a multi-page PDF.
 */
export const downloadReportPdf = ({ topic, result, createdAt, qualityScore }) => {
  if (!result) return;

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginX = 20;
  const marginTop = 20;
  const marginBottom = 20;
  const contentWidth = pageWidth - marginX * 2;
  const lineHeight = 5.5;
  let y = marginTop;

  const ensureSpace = (needed = lineHeight) => {
    if (y + needed > pageHeight - marginBottom) {
      doc.addPage();
      y = marginTop;
    }
  };

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(79, 70, 229);
  const titleLines = doc.splitTextToSize(topic, contentWidth);
  titleLines.forEach((line) => {
    ensureSpace(7);
    doc.text(line, marginX, y);
    y += 7;
  });

  y += 2;

  // Meta
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 120);
  const dateStr = createdAt
    ? new Date(createdAt).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })
    : new Date().toLocaleDateString();
  const meta = qualityScore
    ? `Generated by Literai AI · ${dateStr} · Quality: ${qualityScore}/10`
    : `Generated by Literai AI · ${dateStr}`;
  ensureSpace(5);
  doc.text(meta, marginX, y);
  y += 6;

  doc.setDrawColor(99, 102, 241);
  doc.setLineWidth(0.4);
  ensureSpace(4);
  doc.line(marginX, y, pageWidth - marginX, y);
  y += 8;

  // Body — paginate every line
  doc.setFontSize(10);
  doc.setTextColor(55, 65, 81);
  const plain = markdownToPlainText(result);
  const bodyLines = doc.splitTextToSize(plain, contentWidth);

  bodyLines.forEach((line) => {
    ensureSpace(lineHeight);
    doc.text(line, marginX, y);
    y += lineHeight;
  });

  doc.save(sanitizeFilename(topic));
};

export const copyReportToClipboard = async (result) => {
  if (!result) throw new Error('No report content');
  await navigator.clipboard.writeText(result);
};
